services:
  sandbox-battle-lab-backend:
    container_name: sandbox-battle-lab-backend
    build:
      context: ../../../../
      dockerfile: sandbox/battle-lab/backend/Dockerfile
    image: sandbox-battle-lab-backend:local
    restart: unless-stopped
    env_file:
      - ../.env.production
    ports:
      - '${PORT:-3301}:3301'
